
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProjectRegistry } from "./ProjectRegistry";
export * as factories from "./factories";
export { ProjectRegistry__factory } from "./factories/ProjectRegistry__factory";

    