
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProjectRegistry {
  export type ProjectStruct = {
    title: string;
    description: string;
    tags: string[];
    githubLink: string;
    liveDemoLink: string;
  };

  export type ProjectStructOutput = [
    title: string,
    description: string,
    tags: string[],
    githubLink: string,
    liveDemoLink: string
  ] & {
    title: string;
    description: string;
    tags: string[];
    githubLink: string;
    liveDemoLink: string;
  };
}

export interface ProjectRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getProjects"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getProjects",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getProjects",
    data: BytesLike
  ): Result;
}

export interface ProjectRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProjectRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProjects: TypedContractMethod<
    [],
    [ProjectRegistry.ProjectStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProjects"
  ): TypedContractMethod<[], [ProjectRegistry.ProjectStructOutput[]], "view">;

  filters: {};
}

    