import Image from 'next/image';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { generatePersonalizedGreeting } from '@/ai/flows/personalized-greeting';
import { generatePortfolioSummary } from '@/ai/flows/portfolio-summary';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { personalData, skills, projects, achievements, timeline, passions, socialLinks } from '@/lib/data';
import Link from 'next/link';
import { ExternalLink, Github, Send } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

export default async function Home() {
  const greeting = "Hello, Recruiter!";
  const summary = "I am a skilled blockchain developer with experience in creating decentralized applications. I am passionate about leveraging blockchain technology to build innovative solutions. This summary was generated by AI!";


  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <div className="container mx-auto px-4 md:px-6">

          {/* About Section */}
          <section id="about" className="py-20 md:py-32 grid md:grid-cols-5 gap-8 items-center">
            <div className="md:col-span-3 space-y-4">
              <Badge variant="secondary" className="text-base">{greeting}</Badge>
              <h1 className="text-4xl md:text-6xl font-bold text-primary font-headline">
                Hi, I&apos;m {personalData.name}
              </h1>
              <h2 className="text-2xl md:text-3xl font-medium text-foreground/80 font-headline">
                {personalData.title}
              </h2>
              <p className="text-muted-foreground text-lg">
                {summary}
              </p>
              <div className="flex gap-4 pt-4">
                <Button asChild size="lg">
                  <Link href="#projects">View My Work</Link>
                </Button>
                <Button asChild variant="outline" size="lg">
                   <Link href={socialLinks.linkedin.href} target="_blank">
                    Connect on LinkedIn
                  </Link>
                </Button>
              </div>
            </div>
            <div className="md:col-span-2 flex justify-center">
              <Image
                src={personalData.profileImage}
                alt={personalData.name}
                width={300}
                height={300}
                className="rounded-full shadow-lg border-4 border-primary/20 object-cover"
                data-ai-hint="man portrait"
              />
            </div>
          </section>
          
          <Separator className="my-12" />

          {/* Skills Section */}
          <section id="skills" className="py-16">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">My Skills</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {Object.entries(skills).map(([category, skillList]) => (
                <Card key={category} className="hover:shadow-xl transition-shadow duration-300">
                  <CardHeader>
                    <CardTitle className="text-primary">{category}</CardTitle>
                  </CardHeader>
                  <CardContent className="flex flex-wrap gap-2">
                    {skillList.map(skill => (
                      <Badge key={skill} variant="secondary">{skill}</Badge>
                    ))}
                  </CardContent>
                </Card>
              ))}
            </div>
          </section>

          <Separator className="my-12" />

          {/* Projects Section */}
          <section id="projects" className="py-16">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">Projects</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {projects.map((project) => (
                <Card key={project.title} className="flex flex-col overflow-hidden group hover:scale-105 transition-transform duration-300">
                  <Image src={project.image} alt={project.title} width={600} height={400} className="w-full h-48 object-cover" data-ai-hint={project.dataAiHint}/>
                  <CardHeader>
                    <CardTitle>{project.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="flex-grow flex flex-col">
                    <p className="text-muted-foreground mb-4 flex-grow">{project.description}</p>
                    <div className="flex flex-wrap gap-2 mb-4">
                      {project.technologies.map(tech => (
                        <Badge key={tech} variant="outline">{tech}</Badge>
                      ))}
                    </div>
                    <div className="flex gap-4 mt-auto pt-4">
                      <Button asChild variant="ghost" size="sm">
                        <Link href={project.github} target="_blank" rel="noopener noreferrer">
                          <Github className="mr-2 h-4 w-4" /> GitHub
                        </Link>
                      </Button>
                      <Button asChild variant="ghost" size="sm">
                        <Link href={project.liveDemo} target="_blank" rel="noopener noreferrer">
                          <ExternalLink className="mr-2 h-4 w-4" /> Live Demo
                        </Link>
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </section>

          <Separator className="my-12" />

          {/* Achievements Section */}
          <section id="achievements" className="py-16">
             <h2 className="text-3xl font-bold text-center mb-12 font-headline">Key Achievements</h2>
             <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {achievements.map((achievement) => (
                    <Card key={achievement.title} className="text-center p-6 hover:shadow-primary/20 hover:shadow-lg transition-shadow duration-300">
                        <div className="flex justify-center mb-4">
                            <achievement.icon className="h-12 w-12 text-primary" />
                        </div>
                        <h3 className="text-xl font-semibold mb-2">{achievement.title}</h3>
                        <p className="text-sm text-muted-foreground mb-2">{achievement.date}</p>
                        <p className="text-muted-foreground">{achievement.description}</p>
                    </Card>
                ))}
             </div>
          </section>
          
          <Separator className="my-12" />

          {/* Timeline Section */}
          <section id="timeline" className="py-16">
            <h2 className="text-3xl font-bold text-center mb-16 font-headline">My Journey</h2>
            <div className="relative max-w-2xl mx-auto">
              <div className="absolute left-1/2 h-full w-0.5 bg-border -translate-x-1/2"></div>
              {timeline.map((item, index) => (
                <div key={item.title} className={`mb-8 flex justify-between items-center w-full ${index % 2 === 0 ? 'flex-row-reverse' : ''}`}>
                  <div className="order-1 w-5/12"></div>
                  <div className="z-10 flex items-center order-1 bg-primary shadow-xl w-12 h-12 rounded-full">
                    <item.icon className="mx-auto text-primary-foreground h-6 w-6"/>
                  </div>
                  <div className="order-1 bg-card rounded-lg shadow-xl w-5/12 px-6 py-4">
                    <p className="text-sm text-muted-foreground mb-1">{item.date}</p>
                    <h3 className="font-bold text-lg">{item.title}</h3>
                    <h4 className="font-medium text-primary">{item.company}</h4>
                    <p className="text-sm text-muted-foreground mt-2">{item.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
          
          <Separator className="my-12" />
          
          {/* Passions Section */}
          <section id="passions" className="py-16">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">Passions & Interests</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {passions.map((passion) => (
                <div key={passion.title} className="flex items-start gap-4">
                  <div className="bg-primary/10 p-3 rounded-full">
                    <passion.icon className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold">{passion.title}</h3>
                    <p className="text-muted-foreground mt-1">{passion.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <Separator className="my-12" />

          {/* Connect Section */}
          <section id="connect" className="py-16">
            <h2 className="text-3xl font-bold text-center mb-12 font-headline">Connect With Me</h2>
            <Card className="max-w-2xl mx-auto">
              <CardContent className="pt-6">
                <form className="space-y-4">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="name">Name</Label>
                      <Input id="name" placeholder="Enter your name" />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="email">Email</Label>
                      <Input id="email" type="email" placeholder="Enter your email" />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="message">Message</Label>
                    <Textarea id="message" placeholder="Your message" className="min-h-[150px]" />
                  </div>
                  <div className="flex justify-end">
                    <Button type="submit">
                      <Send className="mr-2 h-4 w-4" />
                      Send Message
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          </section>

        </div>
      </main>
      <Footer />
    </div>
  );
}
